// PayGate.to white-label proxy + German translation
// Generated by the Shopware PayGate plugin (CloudflareSetupService).
// Manual edits are overwritten on next setup run.

const TARGET_API = 'api.paygate.to';
const TARGET_CHECKOUT = 'checkout.paygate.to';

// Filled in by the setup script.
const API_DOMAIN = '__API_DOMAIN__';
const CHECKOUT_DOMAIN = '__CHECKOUT_DOMAIN__';
const AFFILIATE_WALLET = '__AFFILIATE_WALLET__';
const TRANSLATE = __TRANSLATE__;

const TRANSLATIONS = {
    'Complete Your Purchase': 'Bezahlung abschließen',
    'Secure & Encrypted Payment': 'Sichere & verschlüsselte Zahlung',
    'Please select one of the available licensed payment providers to complete your payment. To avoid transaction failure do NOT change values on the payment page. Once a transaction is completed by the selected payment provider you will receive a confirmation email and original merchant website will be instantly notified.':
        'Bitte wähle einen der verfügbaren lizenzierten Zahlungsanbieter aus, um deine Zahlung abzuschließen. Um Fehler zu vermeiden, ändere KEINE Werte auf der Zahlungsseite. Sobald die Zahlung beim gewählten Anbieter abgeschlossen ist, erhältst du eine Bestätigungs-E-Mail und der Online-Shop wird sofort benachrichtigt.',
    'Please complete your purchase at the payment provider page or refresh this page to select another provider. Once a transaction is completed by the selected payment provider you will receive a confirmation email and original merchant website will be instantly notified.':
        'Bitte schließe deine Zahlung beim ausgewählten Anbieter ab oder lade diese Seite neu, um einen anderen Anbieter auszuwählen. Sobald die Zahlung abgeschlossen ist, erhältst du eine Bestätigungs-E-Mail und der Online-Shop wird sofort benachrichtigt.',
    'No payment method selected! Please select a payment method first.':
        'Keine Zahlungsmethode ausgewählt! Bitte wähle zuerst eine Zahlungsmethode aus.',
    'Total Amount': 'Gesamtbetrag',
    'Pay Now': 'Jetzt bezahlen',
    'Payment Processing': 'Zahlung wird verarbeitet',
    'Credit Card': 'Kreditkarte',
    'Bank transfer': 'Banküberweisung',
    'Terms': 'AGB',
    'Privacy': 'Datenschutz',
    'Legal': 'Impressum',
};

addEventListener('fetch', event => {
    event.respondWith(handle(event.request));
});

async function handle(request) {
    const url = new URL(request.url);

    if (url.pathname.startsWith('/control/')) {
        url.hostname = TARGET_API;

        if (url.pathname.endsWith('/wallet.php')
            && AFFILIATE_WALLET
            && !AFFILIATE_WALLET.startsWith('__')) {
            url.pathname = url.pathname.replace('/wallet.php', '/affiliate.php');
            if (!url.searchParams.has('affiliate')) {
                url.searchParams.set('affiliate', AFFILIATE_WALLET);
            }
        }
    } else {
        url.hostname = TARGET_CHECKOUT;

        if (CHECKOUT_DOMAIN
            && !CHECKOUT_DOMAIN.startsWith('__')
            && !url.searchParams.has('domain')) {
            url.searchParams.set('domain', CHECKOUT_DOMAIN);
        }
    }

    const upstream = await fetch(url.toString(), {
        method: request.method,
        headers: request.headers,
        body: (request.method === 'GET' || request.method === 'HEAD') ? undefined : request.body,
        redirect: 'follow',
    });

    const contentType = (upstream.headers.get('content-type') || '').toLowerCase();
    const isHtml = contentType.includes('text/html');

    if (!isHtml) {
        return passthrough(upstream);
    }

    let body = await upstream.text();

    // URL cloaking: rewrite any paygate.to references the upstream page
    // injects into HTML/JS so the customer stays on the merchant subdomain.
    if (CHECKOUT_DOMAIN && !CHECKOUT_DOMAIN.startsWith('__')) {
        body = body.split('https://' + TARGET_CHECKOUT).join('https://' + CHECKOUT_DOMAIN);
        body = body.split('//' + TARGET_CHECKOUT).join('//' + CHECKOUT_DOMAIN);
    }
    if (API_DOMAIN && !API_DOMAIN.startsWith('__')) {
        body = body.split('https://' + TARGET_API).join('https://' + API_DOMAIN);
        body = body.split('//' + TARGET_API).join('//' + API_DOMAIN);
    }

    if (TRANSLATE) {
        body = body.replace('<html lang="en">', '<html lang="de">');
        for (const [en, de] of Object.entries(TRANSLATIONS)) {
            body = body.split(en).join(de);
        }
    }

    const headers = new Headers(upstream.headers);
    headers.delete('content-length');
    headers.delete('content-encoding');
    headers.set('content-type', contentType);

    return new Response(body, {
        status: upstream.status,
        statusText: upstream.statusText,
        headers: headers,
    });
}

function passthrough(upstream) {
    const headers = new Headers(upstream.headers);
    headers.set('Access-Control-Allow-Origin', '*');
    return new Response(upstream.body, {
        status: upstream.status,
        statusText: upstream.statusText,
        headers: headers,
    });
}
